### ISSUE TITLE
代码

### ISSUE THREAD

**Issue by Wu-ZJ** [favoMJ/FRFNet#1]
你好，很激动能看到一篇没有使用预训练模型也能取得这么好的结果的分割论文，不知代码大概何时能开源，已经迫不及待想要复现啦！！！！！

**Comment by Wu-ZJ** [comment]
作者您好，刚刚看完您的论文，首先对您的工作表示感谢！但是我存在以下几点疑问：
1.我看到论文里采用了不同于以往惯例的训练策略，比如说，poly学习率，SGD优化器等？请问作者做过对比实验吗？效果如何？
2.采用了什么样的loss来训练网络呢？跟以往一样的ohem吗？论文里没有交代
3.论文里并没有采用对比试验来证明不同的融合模块，上采样模块的有效性。

**Comment by Wu-ZJ** [comment]
还有一个疑问就是，只把FRFNet的编码部分用resnet-18替代，结果却差了百分之十几，不知道是否有合理的解释，论文里并没有解释。

**Comment by favoMJ** [comment]
我用的是Efficient-Segmentation里面的adam+ohem学习策略，通常是使用sgd的，尚未进行对比实验，融合模块的对比实验会追加考虑的。
resnet-18代替效果骤降的原因尚不清楚。
代码出现一些问题，导致精度骤降，尚未弄清，待弄清后开源，避免产生误导。
